name: Deploy to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set git user (Bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Checkout or create gh-pages branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
          fi


      - name: Remove everything except CNAME
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name 'CNAME' ! -name '.git' -exec rm -rf {} +
          git add -A
          git commit -m "removed old build" || echo "Nothing to commit"
          git push origin gh-pages

      - name: Switch back to main and rebuild
        run: |
          git checkout main
          npm ci
          npm run build

      - name: Switch to gh-pages and copy new build
        run: |
          git checkout gh-pages
          cp -r dist/* .
          rm -rf dist node_modules

      - name: Commit and push new build
        run: |
          git add -A
          git commit -m "Deploying new build" || echo "Nothing to commit"
          git push origin gh-pages